src/Pharmacy/Pharmacy/Models/Insurances/InsuranceModel.cs
using System.ComponentModel.DataAnnotations;

namespace Pharmacy.Models.Insurances
{
    public class InsuranceModel
    {
        public int Id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(64, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        public int SupportedMedicine { get; set; }
    }
}

src/Pharmacy/Pharmacy/Controllers/InsuranceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Data.Entities;
using Pharmacy.Models.Insurances;
using Pharmacy.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    [Ability]
    [Authorize(Roles = PharmacyRoles.Employee)]
    public class InsuranceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;
        public InsuranceController(AppUserManager userManager, AppDbContext context)
        {
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
        }

        public async Task<ActionResult> Index()
        {
            var insurances = await _context.Insurances
                .Include(x => x.Supports)
                .OrderBy(x => x.Name)
                .ToListAsync();
            List<InsuranceModel> model = new List<InsuranceModel>();
            foreach (var item in insurances)
            {
                int supportedMedicine = item.Supports != null ? item.Supports.Count : 0;
                model.Add(new InsuranceModel()
                {
                    Id = item.Id,
                    Name = item.Name,
                    SupportedMedicine = supportedMedicine
                });
            }
            return View(model);
        }

        public ActionResult Add()
        {
            InsuranceModel model = new InsuranceModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(InsuranceModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Insurance insur = new Insurance();
                    insur.Name = model.Name;
                    await _context.Insurances.AddAsync(insur);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    TempData["message"] = ModelState.ErrorGathering();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> Edit(int Id)
        {
            InsuranceModel model = new InsuranceModel();
            var medCat = await _context.Insurances.FirstOrDefaultAsync(x => x.Id.Equals(Id));
            model.Name = medCat.Name;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(InsuranceModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    TempData["message"] = ModelState.ErrorGathering();
                var insur = await _context.Insurances.FirstOrDefaultAsync(x => x.Id.Equals(model.Id));
                if (insur != null)
                {
                    insur.Name = model.Name;
                    _context.Insurances.Update(insur);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    TempData["message"] = "Insurance not found.";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return View();
            }
        }

        public async Task<ActionResult> Delete(int Id)
        {
            var item = await _context.Insurances.FirstOrDefaultAsync(x => x.Id.Equals(Id));
            if (item != null)
            {
                _context.Insurances.Remove(item);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Pharmacy/Pharmacy/Controllers/InsuranceSupportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Models.InsuranceSupport;
using Pharmacy.Models.Medicines;
using Pharmacy.Services.InsuranceService;
using Pharmacy.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    [Ability]
    [Authorize(Roles = PharmacyRoles.Employee)]
    public class InsuranceSupportController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;
        private readonly IInsuranceSupportService _insuranceSupportService;
        public InsuranceSupportController(AppUserManager userManager, AppDbContext context,
            IInsuranceSupportService insuranceSupportService)
        {
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
            _insuranceSupportService = insuranceSupportService ?? throw new Exception(nameof(insuranceSupportService));
        }


        public async Task<ActionResult> Index(int id)
        {
            try
            {
                var insurance = await _context.Insurances
                    .Include(x => x.Supports)
                    .FirstOrDefaultAsync(x => x.Id.Equals(id));
                if (insurance == null)
                    TempData["message"] = "Insurance not found";
                var supported = _context.InsuranceSupports
                    .Include(x => x.Medicine)
                    .Where(x => x.InsuranceId.Equals(insurance.Id))
                    .Select(x => x.Medicine)
                    .Include(x=>x.Products);
                List<MedicineModel> model = new List<MedicineModel>();
                foreach (var item in supported)
                {
                    int supportedByInsurances = item.InsuranceSupports != null ? item.InsuranceSupports.Count : 0;
                    int producedByCompanies = item.Products != null ? item.Products.Count : 0;
                    model.Add(new MedicineModel()
                    {
                        Id = item.Id,
                        Name = item.Name,
                        SupportedByInsurances = supportedByInsurances,
                        ProducedByCompanies = producedByCompanies,
                        Dosage = item.Dosage,
                    });
                }
                ViewBag.Insurance = insurance.Name;
                ViewBag.InsuranceId = insurance.Id;
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["message"] = TempData["message"] == null ? TempData["message"] + ex.Message : TempData["message"];
            }
            return RedirectToAction(nameof(Index),new { id});
        }

        public async Task<ActionResult> SupportMedicine(int id)
        {
            var insurance = await _context.Insurances
                .Include(x => x.Supports)
                .FirstOrDefaultAsync(x => x.Id.Equals(id));
            if (insurance == null)
            {
                TempData["message"] = "Insurance not found";
                return RedirectToAction(nameof(Index), new { id });
            }
            InsuranceSupportModel model = new InsuranceSupportModel();
            model.Insurance = insurance.Id;
            model.InsuranceName = insurance.Name;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> SupportMedicine(InsuranceSupportModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    TempData["message"] = ModelState.ErrorGathering();
                await _insuranceSupportService.SupportMedicineAsync(model);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction(nameof(Index), new { id = model.Insurance });
        }

        public async Task<JsonResult> MedicinesList(int id, string medicine)
        {
            if (!string.IsNullOrWhiteSpace(medicine))
            {
                var insurance = await _context.Insurances.Include(x => x.Supports)
                    .FirstOrDefaultAsync(x => x.Id.Equals(id));
                if (insurance == null)
                    return Json(new object[0]);
                var supported = _context.InsuranceSupports
                    .Include(x => x.Medicine)
                    .Where(x => x.InsuranceId.Equals(insurance.Id))
                    .Select(x => x.Medicine);
                var all = (await _context.Medicines.Where(x => x.Name.Contains(medicine)).ToListAsync());
                if (supported.Any())
                    all = all.Except(supported).ToList();

                var medicines = all
                    .OrderBy(x => x.Name)
                    .Select(x => new { Name = $"{x.Name} - {x.Dosage}", x.Id });
                if (medicines.Any())
                    return Json(medicines);
                else
                    return Json(new object[0]);
            }
            return Json(new object[0]);
        }

    }
}

src/Pharmacy/Pharmacy/Views/Insurance/Add.cshtml
@model Pharmacy.Models.Insurances.InsuranceModel
@{
    ViewData["Title"] = "Create new insurance";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-9 col-md-offset-2">
        <form method="post">
            <h4>Create a insurance</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-md-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Pharmacy/Pharmacy/Views/Insurance/Edit.cshtml
@model Pharmacy.Models.Insurances.InsuranceModel
@{
    ViewData["Title"] = "Edit insurance " + Model.Name;
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-9 col-md-offset-2">
        <form method="post">
            <h4>Edit a insurance</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-md-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Pharmacy/Pharmacy/Views/Insurance/Index.cshtml
@model List<Pharmacy.Models.Insurances.InsuranceModel>
@{
    ViewBag.Title = "Cateogories";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <a class="btn btn-success" asp-controller="Insurance" asp-action="Add">Add new insurance</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Supported Medicines
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.SupportedMedicine</td>
                            <td>
                                <a class="btn btn-sm btn-warning" asp-controller="insurance" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                <a class="btn btn-sm btn-danger" asp-controller="insurance" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                <a class="btn btn-sm btn-primary" asp-controller="InsuranceSupport" asp-action="Index" asp-route-id="@item.Id">Supported Medicines</a>

                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6">No insurance already exist.</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}