src/Pharmacy/Pharmacy/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Models.Admin;
using Pharmacy.Models.Users;
using Pharmacy.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    [Authorize(Roles = PharmacyRoles.Admin)]
    public class AdminController : Controller
    {
        private readonly IUserService _userService;
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;

        public AdminController(IUserService userService, AppUserManager userManager, AppDbContext context)
        {
            _userService = userService ?? throw new Exception(nameof(userService));
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
        }

        public ActionResult NewAdmin()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> NewAdmin(RegisterAdminModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _userService.RegisterAdminAsync(model);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View();
                }
            }
            else
                return View();
        }

        public async Task<ActionResult> ListOfAttempts()
        {
            List<AttemptedUser> attemptedUsers = new List<AttemptedUser>();
            try
            {
                var docs = _context.Doctors.Include(x => x.User).Where(x => x.State == UserStates.Deactive);
                var doctorsAttempted = docs.Select(x => new AttemptedUser(x.User.UserName, UserTypes.Doctor.ToString()));
                var emps = _context.Employees.Include(x => x.User).Where(x => x.State == UserStates.Deactive);
                var employeeAttempted = emps.Select(x => new AttemptedUser(x.User.UserName, UserTypes.Employee.ToString()));
                attemptedUsers = await doctorsAttempted.Union(employeeAttempted).ToListAsync();
                return View(attemptedUsers);
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.Message;
                return View(attemptedUsers);
            }
        }

        public async Task<ActionResult> ActivateUser(string username, string type)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (type.ToLower().Equals(UserTypes.Doctor.ToString().ToLower()))
                    {
                        await _userService.ActiveDoctorAsync(username);
                    }
                    else if (type.ToLower().Equals(UserTypes.Employee.ToString().ToLower()))
                    {
                        await _userService.ActiveEmployeeAsync(username);
                    }
                    return RedirectToAction(nameof(ListOfAttempts));
                }
                catch (Exception ex)
                {
                    TempData["message"] = ex.Message;
                    return RedirectToAction(nameof(ListOfAttempts));
                }
            }
            else
                return RedirectToAction(nameof(ListOfAttempts));
        }

        public async Task<ActionResult> DeactivateUser(string username, string type)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (type.ToLower().Equals(UserTypes.Doctor.ToString().ToLower()))
                    {
                        await _userService.DeactiveDoctorAsync(username);
                    }
                    else if (type.ToLower().Equals(UserTypes.Employee.ToString().ToLower()))
                    {
                        await _userService.DeactiveEmployeeAsync(username);
                    }
                    return RedirectToAction(nameof(ListOfAttempts));
                }
                catch (Exception ex)
                {
                    TempData["message"] = ex.Message;
                    return RedirectToAction(nameof(ListOfAttempts));
                }
            }
            else
                return RedirectToAction(nameof(ListOfAttempts));
        }
    }
}

src/Pharmacy/Pharmacy/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Data.Entities;
using Pharmacy.Models.Orders;
using Pharmacy.Services;
using Pharmacy.Services.OrderService;
using Pharmacy.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    [Ability]
    [Authorize(Roles = PharmacyRoles.Patient)]
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        public OrderController(AppUserManager userManager, AppDbContext context,
            IOrderService orderService, IUserService userService)
        {
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
            _orderService = orderService ?? throw new Exception(nameof(orderService));
            _userService = userService ?? throw new Exception(nameof(userService));
        }

        public async Task<ActionResult> Index()
        {
            try
            {
                var patient = await _userService.GetCurrentUserAsync<Patient>(UserTypes.Patient) as Patient;
                if (patient == null)
                    throw new Exception("user is not a patient.");
                var orders = await _context.Orders.Include(x => x.OrderDetails)
                    .Where(x => x.PatientId.Equals(patient.Id)).ToListAsync();
                List<OrderInfoModel> orderInfoModel = new List<OrderInfoModel>();
                var orderIds = orders.Select(x => x.Id);
                var details = await _context.OrderDetails.Include(x => x.Product).Where(x => orderIds.Contains(x.OrderId)).ToListAsync();
                foreach (var item in orders)
                {
                    var totalPrice = details.Where(x=>x.OrderId.Equals(item.Id)).Sum(x => x.Product.Price);
                    var status = item.Status;
                    orderInfoModel.Add(new OrderInfoModel() { Status = status, TotalPrice = totalPrice });
                }
                return View(orderInfoModel);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<ActionResult> NewOrder(int id)
        {
            try
            {
                OrderListModel orderList = new OrderListModel();
                var patient = await _userService.GetCurrentUserAsync<Patient>(UserTypes.Patient) as Patient;
                if (patient == null)
                    throw new Exception("user is not a patient!");
                var patientInsurances = await _context.PatientInsurances.Include(x => x.Insurance).ThenInclude(x => x.Supports)
                    .Where(x => x.PatientId.Equals(patient.Id)).ToListAsync();
                var script = await _context.Scripts.Include(x => x.ScriptDetails)
                    .FirstOrDefaultAsync(x => x.Id.Equals(id));
                if (script == null)
                    throw new Exception("script not found");
                var scriptDetailsProducts = script.ScriptDetails.Select(x => x.MedicineId).ToList();
                var availableProducts = _context.Products.Include(x => x.Medicine)
                    .Include(x => x.Company)
                    .Where(x => scriptDetailsProducts.Contains(x.MedicineId));
                List<OrderModel> products = new List<OrderModel>();
                var patientInsurancesIds = patientInsurances.Select(x => x.InsuranceId);
                var patientInsurancesSupports = await _context.InsuranceSupports
                    .Where(x => patientInsurancesIds.Contains(x.InsuranceId)).ToListAsync();
                var order = await _context.Orders.FirstOrDefaultAsync(x => x.ScriptId.Equals(script.Id));
                List<OrderModel> basketItems = new List<OrderModel>();
                List<Product> availableBasketItems = new List<Product>();
                if (order != null)
                {
                    var orderDetails = await _context.OrderDetails
                        .Include(x => x.Product).ThenInclude(x => x.Medicine)
                        .Include(x => x.Product).ThenInclude(x => x.Company)
                        .Where(x => x.OrderId.Equals(order.Id)).ToListAsync();
                    var orderedDetails = orderDetails.Where(x => x.Status == OrderStatuses.Ordered);
                    var orderedDetailsIds = orderedDetails.Select(x => x.Product.MedicineId);
                    availableBasketItems = orderDetails.Select(x => x.Product).ToList();
                    var availableBasketItemsIds = availableBasketItems.Select(x => x.MedicineId);
                    //var orderedItems = orderDetails.Select(x=>x.Product).ToList(
                    availableProducts = availableProducts.Where(x => !availableBasketItemsIds.Contains(x.MedicineId));
                    availableProducts = availableProducts.Where(x => !orderedDetailsIds.Contains(x.MedicineId));

                    orderDetails = orderDetails.Where(x => !orderedDetailsIds.Contains(x.Product.MedicineId)).ToList();

                    foreach (var oDetails in orderDetails)
                    {
                        var supportedByInsurances = patientInsurancesSupports.Intersect(oDetails.Product.Medicine.InsuranceSupports);
                        bool supportedByInsurance = supportedByInsurances.Any();
                        var supportedByInsuranceIds = supportedByInsurances.Select(x => x.InsuranceId);
                        var supportedByInsuranceNames = (await _context.Insurances.Where(x => supportedByInsuranceIds.Contains(x.Id))
                            .ToListAsync())
                            .Select(x => x.Name);
                        basketItems.Add(new OrderModel()
                        {
                            Id = oDetails.Id,
                            ScriptId = script.Id,
                            CompanyName = oDetails.Product.Company.Name,
                            ProductExistence = oDetails.Product.Quantity,
                            ProductExpireDate = oDetails.Product.ExpireDate,
                            ProductPrice = supportedByInsurance == true ? 0 : oDetails.Product.Price,
                            MedicineName = oDetails.Product.Medicine.Name,
                            MedicineDosage = oDetails.Product.Medicine.Dosage,
                            SupportByInsurance = supportedByInsurance,
                            Insurance = string.Join(',', supportedByInsuranceNames)
                        });
                    }
                }
                orderList.Basket = basketItems;

                foreach (var item in availableProducts)
                {
                    var supportedByInsurances = patientInsurancesSupports.Intersect(item.Medicine.InsuranceSupports);
                    bool supportedByInsurance = supportedByInsurances.Any();
                    var supportedByInsuranceIds = supportedByInsurances.Select(x => x.InsuranceId);
                    var supportedByInsuranceNames = (await _context.Insurances.Where(x => supportedByInsuranceIds.Contains(x.Id))
                        .ToListAsync())
                        .Select(x => x.Name);
                    products.Add(new OrderModel()
                    {
                        Id = item.Id,
                        ScriptId = script.Id,
                        CompanyName = item.Company.Name,
                        MedicineName = item.Medicine.Name,
                        MedicineDosage = item.Medicine.Dosage,
                        ProductExpireDate = item.ExpireDate,
                        ProductPrice = item.Price,
                        ProductExistence = item.Quantity,
                        SupportByInsurance = supportedByInsurance,
                        Insurance = string.Join(',', supportedByInsuranceNames)
                    });
                }
                orderList.Products = products;

                return View(orderList);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> Checkout()
        {
            try
            {
                await _orderService.CheckOutAsync();
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> AddToBasket(int productId, int scriptId)
        {
            try
            {
                var script = await _context.Scripts.FirstOrDefaultAsync(x => x.Id.Equals(scriptId));
                if (script == null)
                    throw new Exception("script not found.");
                var orderResult = await _orderService.OrderNewItemAsync(new NewOrderModel()
                {
                    Script = script.Id,
                    Products = new List<int>() { productId }
                });

                return RedirectToAction(nameof(NewOrder), new { id = scriptId, orderId = orderResult.Id });
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> DeleteFromBasket(int orderDetailId, int scriptId)
        {
            try
            {
                var orderDetail = await _context.OrderDetails.FirstOrDefaultAsync(x => x.Id.Equals(orderDetailId));

src/Pharmacy/Pharmacy/Controllers/PatientScriptController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Data.Entities;
using Pharmacy.Models.Scripts;
using Pharmacy.Services;
using Pharmacy.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    [Authorize(Roles = PharmacyRoles.Patient)]
    public class PatientScriptController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;
        private readonly IUserService _userService;

        public PatientScriptController(AppUserManager userManager, AppDbContext context,
            IUserService userService)
        {
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
            _userService = userService ?? throw new Exception(nameof(userService));
        }

        public async Task<ActionResult> Index()
        {
            try
            {
                var patient = await _userService.GetCurrentUserAsync<Patient>(UserTypes.Patient) as Patient;
                if (patient == null)
                    throw new Exception("user is not a patient");
                var scripts = await _context.Scripts
                    .Where(x => x.PatientId.Equals(patient.Id))
                    .ToListAsync();
                return View(scripts);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> Detail(int id)
        {
            try
            {
                var patient = await _userService.GetCurrentUserAsync<Patient>(UserTypes.Patient) as Patient;
                if (patient == null)
                    throw new Exception("user is not a patient");
                var script = await _context.Scripts
                    .Include(x => x.Patient)
                    .Include(x => x.Doctor)
                    .Include(x => x.ScriptDetails).ThenInclude(y => y.Medicine)
                    .FirstOrDefaultAsync(x => x.PatientId.Equals(patient.Id) && x.Id.Equals(id));
                var order = await _context.Orders
                    .FirstOrDefaultAsync(x => x.ScriptId.Equals(script.Id));
                if (order != null)
                    if (order.Status == OrderStatuses.Ordered)
                        ViewData["AlreadyOrdered"] = true;
                return View(script);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Delete(int Id)
        {
            var item = await _context.Scripts.FirstOrDefaultAsync(x => x.Id.Equals(Id));
            if (item != null)
            {
                _context.Scripts.Remove(item);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Pharmacy/Pharmacy/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<a href="http://www.amirhosseinghorbani.com">DEV</a>

src/Pharmacy/Pharmacy/Views/Home/Index.cshtml
@model Pharmacy.Models.HomeModel
@{
    ViewData["Title"] = "Home Page";
}

@if (Model.Active != null)
{
    if (!Model.Active.Value)
    {
        <div class="alert alert-warning">
            <h4>
                You're account is not active, admin might disabled you're account or not activate yet!
            </h4>
        </div>
    }
}

@if (User.IsInRole(Pharmacy.Data.PharmacyRoles.Admin))
{
    <div class="row" style="margin:10px 0px">
        <div class="col-md-12">
            <div class="col-md-3">
                <button class="btn btn-primary btn-lg" style="padding:30px;width:275px">
                    <i class="fa fa-user-secret fa-2x"></i> Admins <span class="badge">@Model.AdminCount</span>
                </button>
            </div>
            <div class="col-md-3">
                <button class="btn btn-info btn-lg" style="padding:30px;width:275px">
                    <i class="fa fa-users fa-2x"></i>  Employees <span class="badge">@Model.EmployeeCount</span>
                </button>
            </div>
            <div class="col-md-3">
                <button class="btn btn-warning btn-lg" style="padding:30px;width:275px">
                    <i class="fa fa-user-md fa-2x"></i> Doctors <span class="badge">@Model.DoctorCount</span>
                </button>
            </div>
            <div class="col-md-3">
                <button class="btn btn-success btn-lg" style="padding:30px;width:275px">
                    <i class="fa fa-user-injured fa-2x"></i>  Patients <span class="badge">@Model.PatientCount</span>
                </button>
            </div>
        </div>
    </div>

    <div class="panel panel-primary" style="margin:10px 0px">
        <div class="panel-heading">
            <h3 class="panel-title">Admin Dashboard</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-lg btn-default" asp-controller="Admin" asp-action="NewAdmin">Add new admin <i class="fa fa-user-secret"></i></a>
            <a class="btn btn-lg btn-default" asp-controller="Admin" asp-action="ListOfAttempts">List of attempted users <i class="fa fa-paper-plane"></i></a>
            <a class="btn btn-lg btn-default" asp-controller="Doctor" asp-action="ListOfLicenses">List of doctor licenses <i class="fa fa-address-card"></i></a>
        </div>
    </div>
}

@if (User.IsInRole(Pharmacy.Data.PharmacyRoles.Employee))
{
    <div class="row" style="margin:10px 0px">
        <div class="col-md-12">
            <div class="col-md-3">
                <a class="btn btn-primary btn-lg" style="padding:30px;width:275px" asp-controller="Medicine" asp-action="Index">
                    <i class="fa fa-capsules fa-2x"></i> Medicines <span class="badge">@Model.MedicineCount</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-info btn-lg" style="padding:30px;width:275px" asp-controller="MedicineCategory" asp-action="Index">
                    <i class="fa fa-tags fa-2x"></i>  Medicine Categories <span class="badge">@Model.MedicineCategoryCount</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-warning btn-lg" style="padding:30px;width:275px" asp-controller="Insurance" asp-action="Index">
                    <i class="fa fa-shield-alt fa-2x"></i> Insurances <span class="badge">@Model.InsuranceCount</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-success btn-lg" style="padding:30px;width:275px" asp-controller="Product" asp-action="Index">
                    <i class="fa fa-pills fa-2x"></i>  Products <span class="badge">@Model.ProductCount</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row" style="margin:10px 0px">
        <div class="col-md-12">
            <div class="col-md-3">
                <a class="btn btn-primary btn-lg" style="padding:30px;width:275px" asp-controller="Employee" asp-action="OrderList">
                    <i class="fa fa-shopping-cart fa-2x"></i> Orders <span class="badge">@Model.OrderCount</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-info btn-lg" style="padding:30px;width:275px" asp-controller="Employee" asp-action="ScriptList">
                    <i class="fa fa-medkit fa-2x"></i>  Scripts <span class="badge">@Model.ScriptCount</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-warning btn-lg" style="padding:30px;width:275px" asp-controller="Doctor" asp-action="ListOfLicenses">
                    <i class="fa fa-address-card fa-2x"></i> Doctor Licenses <span class="badge">@Model.DoctorLicenses</span>
                </a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-success btn-lg" style="padding:30px;width:275px" asp-controller="Company" asp-action="Index">
                    <i class="fa fa-building fa-2x"></i>  Companies <span class="badge">@Model.CompanyCount</span>
                </a>
            </div>
        </div>
    </div>
    <div class="panel panel-primary" style="margin-top:50px">
        <div class="panel-heading">
            <h3 class="panel-title">Employee Dashboard</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <a class="btn btn-lg btn-default" style="margin:2px" asp-controller="Medicine" asp-action="Add">Add new medicine <i class="fa fa-pills"></i></a>
                <a class="btn btn-lg btn-default" style="margin:2px" asp-controller="MedicineCategory" asp-action="Add">Add new medicine category <i class="fa fa-tags"></i></a>
                <a class="btn btn-lg btn-default" style="margin:2px" asp-controller="Insurance" asp-action="Add">Add new insurance <i class="fa fa-shield-alt"></i></a>
                <a class="btn btn-lg btn-default" style="margin:2px" asp-controller="Company" asp-action="Index">Add new company <i class="fa fa-building"></i></a>
                <a class="btn btn-lg btn-default" style="margin:2px" asp-controller="#" asp-action="#">Reports <i class="fa fa-chart-bar"></i></a>
            </div>
        </div>
    </div>
}

@if (User.IsInRole(Pharmacy.Data.PharmacyRoles.Doctor))
{
    <div class="row" style="margin:10px 0px">
        <div class="col-md-12">
            <div class="col-md-4 col-md-offset-2">
                <a class="btn btn-primary btn-lg" style="padding:30px;width:275px" asp-controller="Script" asp-action="Index">
                    <i class="fa fa-capsules fa-2x"></i> Scripts <span class="badge">@Model.CurrentDoctorScripts</span>
                </a>
            </div>
            <div class="col-md-4">
                <a class="btn btn-info btn-lg" style="padding:30px;width:275px" asp-controller="DoctorLicense" asp-action="Index">
                    <i class="fa fa-tags fa-2x"></i>  Licenses <span class="badge">@Model.CurrentDoctorLicenses</span>
                </a>
            </div>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Doctor Dashboard</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-lg btn-default" asp-controller="DoctorLicense" asp-action="NewLicense">New License <i class="fa fa-user-circle"></i></a>
        </div>
    </div>
}

@if (User.IsInRole(Pharmacy.Data.PharmacyRoles.Patient))
{
    <div class="row" style="margin:10px 0px">
        <div class="col-md-12">
            <div class="col-md-4">
                <a class="btn btn-success btn-lg" asp-controller="PatientScript" asp-action="Index" style="padding:30px;width:275px">
                    <i class="fa fa-capsules fa-2x"></i> Scripts <span class="badge">@Model.CurrentPatientScripts</span>
                </a>
            </div>
            <div class="col-md-4">
                <a class="btn btn-info btn-lg" style="padding:30px;width:275px" asp-controller="Order" asp-action="Index">
                    <i class="fa fa-credit-card fa-2x"></i>  Orders <span class="badge">@Model.CurrentPatientOrders</span>
                </a>
            </div>
            <div class="col-md-4">
                <a class="btn btn-primary btn-lg" href="#" style="padding:30px;width:275px">
                    <i class="fa fa-shopping-basket fa-2x"></i> Basket <span class="badge">@Model.CurrentPatientBasketItems</span>
                </a>
            </div>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Patient Dashboard</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-lg btn-default" asp-controller="#" asp-action="#">Manage Profile <i class="fa fa-user-circle"></i></a>
            <a class="btn btn-lg btn-default" asp-controller="Script" asp-action="RequestScript">Request new script <i class="fa fa-syringe"></i></a>
            <a class="btn btn-lg btn-primary" asp-controller="Order" asp-action="Checkout">Checkout! <i class="fa fa-credit-card"></i></a>
        </div>
    </div>
}


@if (!User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-md-12">
            <h2>If you are not already a part of this amazing Pharmacy system <a class="btn btn-default" style="text-transform: uppercase;" asp-area="Identity" asp-page="/Account/Register">let's Register</a></h2>
        </div>
    </div>
}