src/Pharmacy/Pharmacy/Controllers/DoctorLicenseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pharmacy.Data;
using Pharmacy.Data.Entities;
using Pharmacy.Models.Doctors;
using System.Threading.Tasks;
using Pharmacy.Services;
using Pharmacy.Utilities;
using System;

namespace Pharmacy.Controllers
{
    [Ability]
    [Authorize(Roles = PharmacyRoles.Doctor)]
    public class DoctorLicenseController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppUserManager _userManager;
        private readonly IUserService _userService;
        public DoctorLicenseController(AppUserManager userManager, AppDbContext context, IUserService userService)
        {
            _userManager = userManager ?? throw new Exception(nameof(userManager));
            _context = context ?? throw new Exception(nameof(context));
            _userService = userService ?? throw new Exception(nameof(userService));
        }


        public async Task<ActionResult> Index()
        {
            try
            {
                var currentDoctor = await _userService.GetCurrentUserAsync<Doctor>(UserTypes.Doctor) as Doctor;
                if (currentDoctor == null)
                    throw new Exception("user is not a doctor");
                var doc = await _context.Doctors.Include(x => x.Licenses)
                    .FirstOrDefaultAsync(x => x.Id.Equals(currentDoctor.Id));
                if(doc == null)
                    throw new Exception("doctor not found");
                return View(doc.Licenses);
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult NewLicense()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> NewLicense(LicenseModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var doc = await _userService.GetCurrentUserAsync<Doctor>(UserTypes.Doctor) as Doctor;
                    if (doc == null)
                        throw new Exception("user is not a doctor");
                    Data.Entities.DoctorLicense license = new Data.Entities.DoctorLicense();
                    license.Title = model.Title;
                    license.DoctorId = doc.Id;
                    license.Status = DoctorLicenseStatuses.Pending;
                    await _context.DoctorLicenses.AddAsync(license);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    TempData["message"] = ModelState.ErrorGathering();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> DeleteLicense(int id)
        {
            try
            {
                var license = await _context.DoctorLicenses.FindAsync(id);
                if (license == null)
                    throw new Exception("license not found");
                if (license.Status != DoctorLicenseStatuses.Pending)
                    throw new Exception("license status must be Pending. (otherwise you are not able to delete it)");
                _context.DoctorLicenses.Remove(license);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

src/Pharmacy/Pharmacy/Views/DoctorLicense/Index.cshtml
@model IEnumerable<Pharmacy.Data.Entities.DoctorLicense>
@{
    ViewBag.Title = "Doctor Licenses";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <a class="btn btn-success" asp-controller="DoctorLicense" asp-action="NewLicense">Add new license</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Status
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        string itemClass = string.Empty;
                        switch (item.Status)
                        {
                            case Pharmacy.Data.DoctorLicenseStatuses.Rejected:
                                itemClass = "class=license-rejected-item";
                                break;
                            case Pharmacy.Data.DoctorLicenseStatuses.Accepted:
                                itemClass = "class=license-accepted-item";
                                break;
                            case Pharmacy.Data.DoctorLicenseStatuses.Pending:
                                itemClass = "class=license-pending-item";
                                break;
                        }

                        <tr @(itemClass)>
                            <td>@item.Title</td>
                            <td>@item.Status.ToString()</td>
                            @if (item.Status == Pharmacy.Data.DoctorLicenseStatuses.Pending)
                            {
                                <td>
                                    <a class="btn btn-sm btn-danger" asp-controller="DoctorLicense" asp-action="DeleteLicense" asp-route-id="@item.Id">Delete</a>
                                </td>
                            }
                            else
                            {
                                <td>
                                    &nbsp;
                                </td>
                            }
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6">No License already exist.</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Pharmacy/Pharmacy/Views/DoctorLicense/NewLicense.cshtml
@model Pharmacy.Models.Doctors.LicenseModel
@{
    ViewData["Title"] = "Add new license";
}
<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-9 col-md-offset-2">
        <form method="post">
            <h4>Add new license</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label asp-for="Title"></label>
                </div>
                <div class="col-md-8">
                    <input asp-for="Title" class="form-control text-center" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}